### ISSUE TITLE
Auto apply syntax when open CMakeLists.txt

### ISSUE THREAD

**Issue by thangdc94** [zyxar/Sublime-CMakeLists#12]
When I open a CMakeLists.txt file in Sublime Text 3, I have to choose `View > Syntax > Cmake`. Is there a way to use syntax automatically?

**Comment by zyxar** [comment]
When open a file named `CMakeLists.txt` or `*.cmake` in Sublime Text 2/3, the syntax is automatically applied.
I cannot reproduce your issue locally. But maybe your cmake file is not *exactly* named as `CMakeLists.txt`? Try upgrading to latest package? Or you have other cmake related packages installed?

**Comment by thangdc94** [comment]
After I restart Sublime Text a few times, now it apply automatically. Thank you for your support.
