### ISSUE TITLE
Import fixes from twxs/vs.language.cmake

### ISSUE THREAD

**Issue by darthwalsh** [zyxar/Sublime-CMakeLists#31]
The [VS Code CMake](https://github.com/twxs/vs.language.cmake) extension forked and [changed the tmLanguage](https://github.com/twxs/vs.language.cmake/commits/master/syntaxes/CMake.tmLanguage) to fix some issues.

It would be good to merge those fixes back here.

**Comment by rwols** [comment]
We use a .sublime-syntax file now. But I’m sure it can be of help for people still on ST2.

**Comment by rwols** [comment]
The amount of ST2 users is close to 0% according to data from package control.
