### ISSUE TITLE
FILE sometimes not highlighted

### ISSUE THREAD

**Issue by tdegeus** [zyxar/Sublime-CMakeLists#35]
The keyword `FILE` is sometimes not highlighted. See these screenshots:

<img width="457" alt="Screenshot 2019-12-10 at 13 20 34" src="https://user-images.githubusercontent.com/7030445/70529098-0a28c880-1b50-11ea-94f9-3a5688e32af1.png">

<img width="441" alt="Screenshot 2019-12-10 at 13 22 21" src="https://user-images.githubusercontent.com/7030445/70529147-262c6a00-1b50-11ea-88c5-7b79882352f1.png">

**Comment by rwols** [comment]
This is an oversight and we should update the built-ins :)

**Comment by tdegeus** [comment]
Sounds good. Thanks for the nice library!
