### ISSUE TITLE
Package no longer appears in list of available packages

### ISSUE THREAD

**Issue by Dekken** [zyxar/Sublime-CMakeLists#39]
Possibly because of the message seen @ https://packagecontrol.io/packages/CMake

> Package info was unavailable last time crawler ran. 
> Unable to download https://api.github.com/repos/zyxar/Sublime-CMakeLists after 3 attempts

**Comment by rwols** [comment]
This wasn't particular to this package, almost all packages were missing. For reasons unknown to me, they're back.

**Comment by Dekken** [comment]
cheers @rwols
