### ISSUE TITLE
variable completion triggers are lowercase

### ISSUE THREAD

**Issue by rwols** [zyxar/Sublime-CMakeLists#55]
Should these stay lowercase or should they be uppercase?

IMO they should be uppercase because we want to stay on the path of least astonishment. It's odd that my triggers suddenly turn into an uppercased replacement of the lowercase trigger.

**Comment by arcturus140** [comment]
it looks indeed much better with suggestions in uppercase. Completions are still triggered case insensitive. I am happy with the change.
