### ISSUE TITLE
install programs is not highlighted

### ISSUE THREAD

**Issue by arcturus140** [zyxar/Sublime-CMakeLists#58]
for `install({`FILES`_ | `PROGRAMS`_} <file>... [...])` the `PROGRAMS` variant is not highlighted. Could this be the responsible part here:

https://github.com/zyxar/Sublime-CMakeLists/blob/eb92b766c04db49bb120a9877b6bcd41d9333714/CMakeCommands.sublime-syntax#L892-L896

? Perhaps it should be match: `\bPROGRAMS\b`. I changed it but it didn't make a difference.

**Comment by arcturus140** [comment]
Btw why are there still tmLanguage files? Is this for historical reason only? Are they used for backwards compatibility?

**Comment by rwols** [comment]
To modify keywords of built-in commands:

1. Edit CMakeCommands.yml
2. Run tools/update-commands.py

> Are they used for backwards compatibility?

Indeed.
