### ISSUE TITLE
Single-quoted strings shouldn't be highlighted

### ISSUE THREAD

**Issue by lastsecondsave** [zyxar/Sublime-CMakeLists#61]
CMake treats single quotes as a character, they do not define a string. For example this script:
```
cmake_minimum_required(VERSION 3.19)
project(quotes)
message(WARNING 'quotes are still here')
```
will print:
```
CMake Warning at CMakeLists.txt:3 (message):
  'quotesarestillhere'
```
The syntax does highlight single quotes and this may confuse you. Which makes the resuling build error a bit annoying.

**Comment by arcturus140** [comment]
i didn't read the syntax definiton for CMake very extensively. There's no single-quoted string so i think removing it is all that needs to be done.
