### ISSUE TITLE
Parser is broken for arguments with parenthesis

### ISSUE THREAD

**Issue by ratijas** [zyxar/Sublime-CMakeLists#68]
Parser is broken for arguments with parenthesis.

See example below. At the end of the first line, syntax highlighting engine returns to the global `main` context.

_Qt6/qtdeclarative/src/qml/CMakeLists.txt:_

```cmake
qt_internal_extend_target(Qml CONDITION MSVC AND (TEST_architecture_arch STREQUAL "i386")
    LINK_OPTIONS
        "/BASE:0x66000000"
)

qt_internal_extend_target(Qml CONDITION MSVC
    DEFINES
        _CRT_SECURE_NO_WARNINGS
)
```
![Example](https://user-images.githubusercontent.com/6737986/133506526-c0f93a13-38b0-478f-be7b-07b7188bdf2d.png)

### Version

Sublime Text: Build 4113
Sublime-CMakeLists: 1.2.0

**Comment by rwols** [comment]
@arcturus140 do you want to tackle this?

**Comment by arcturus140** [comment]
Thank you for reporting this. I can replicate it on ST3. 

I'll take care of it, but the following days i am occupied with other tasks. I expect to get to this next week.

**Comment by ratijas** [comment]
Is there any reason left to stick to ST3? o_O

**Comment by arcturus140** [comment]
ST4 provides mechanisms that allow backward compatibility with ST3

**Comment by ratijas** [comment]
> ST4 provides mechanisms that allow backward compatibility with ST3

Yes, there is one. Yet, why would you live with it? That's the question.
